In [ ]:
# MOwNiT
## Laboratorium 1
### Analiza danych - DataFrames

- Zaawansowany pakiet do działania na tabelkach nxm danych 
- Podobne do pandas DataFrames w Pythonie albo data.frame w R
- Specjalistyczne funkcje do statystyki
- W przypadku włąsnej instalacji należy zaistalować pakiet:

```julia
Pkg.add("DataFrames")
```

- DataFrame to rodzaj bazy danych in-memory
- Składa się z kolumn, do których odwołujemy się używając symboli
- Każda z kolumn może przechowywać inny typ (inaczej niż w dwuwymiarowych tablicach )
- każda z kolumn jest typu Array{T,1} gdzie T jest okreslonym typem danych (np. Float64)
- strona pakietu: https://github.com/JuliaStats/DataFrames.jl
- dokumentacja najnowszej wersji: https://juliadata.github.io/DataFrames.jl/stable/index.html





In [1]:
# za pierwszym razem, jeśli uruchamiamy lokalnie to instalujemy 
#using Pkg
#Pkg.add("DataFrames")

In [2]:
# Tworzenie DataFrame
using DataFrames
df1=DataFrame()
df1.MojaKolumna= 1:4
df1.x2= [4,pi,sqrt(2), 42]
df1.Col3= [true,false, true, false]
show(df1)

4×3 DataFrame
 Row │ MojaKolumna  x2        Col3  
     │ Int64        Float64   Bool  
─────┼──────────────────────────────
   1 │           1   4.0       true
   2 │           2   3.14159  false
   3 │           3   1.41421   true
   4 │           4  42.0      false

In [3]:
# Wybieranie kolumn
# ! - nie tworzy kopii (zwraca referencję), : - tworzy kopię
typeof(df1[!,2])

Vector{Float64} (alias for Array{Float64, 1})

In [4]:
typeof(df1[:,2])

Vector{Float64} (alias for Array{Float64, 1})

In [5]:
df1[:, :x2] == df1[!, :x2]  # true bc the same values

true

In [6]:
df1[:, :x2] === df1[!, :x2] # false bc not the same vectors

false

In [7]:
typeof(df1.Col3)

Vector{Bool} (alias for Array{Bool, 1})

In [8]:
# możemy też utworzyć DataFrame używając konstruktora
df2=DataFrame(MojaKolumna=1:10, 
    Col2=[2,pi, sqrt(2), 3, 4,2,pi, sqrt(2), 3, 4], 
    Col3=[true,true,false,true,false,true,true,false,true,false])

10×3 DataFrame
 Row │ MojaKolumna  Col2     Col3  
     │ Int64        Float64  Bool  
─────┼─────────────────────────────
   1 │           1  2.0       true
   2 │           2  3.14159   true
   3 │           3  1.41421  false
   4 │           4  3.0       true
   5 │           5  4.0      false
   6 │           6  2.0       true
   7 │           7  3.14159   true
   8 │           8  1.41421  false
   9 │           9  3.0       true
  10 │          10  4.0      false

In [9]:
# liczba wierszy
size(df2, 1) 

10

In [10]:
# liczba kolumn
size(df2, 2) 

3

In [11]:
# można odwoływać się po indeksie
show(df2[:,2])

[2.0, 3.141592653589793, 1.4142135623730951, 3.0, 4.0, 2.0, 3.141592653589793, 1.4142135623730951, 3.0, 4.0]

In [12]:
# albo po symbolu kolumny
show(df2[!,:Col2])

[2.0, 3.141592653589793, 1.4142135623730951, 3.0, 4.0, 2.0, 3.141592653589793, 1.4142135623730951, 3.0, 4.0]

In [13]:
# wiersze lub podzbiory wierszy i kolumn uzyskujemy poprzez operator (:). Wynikiem jest nowy DataFrame
show(df2[3,:])

DataFrameRow
 Row │ MojaKolumna  Col2     Col3  
     │ Int64        Float64  Bool  
─────┼─────────────────────────────
   3 │           3  1.41421  false

In [14]:
# drugi i trzeci wiersz
df2[2:3, :]

2×3 DataFrame
 Row │ MojaKolumna  Col2     Col3  
     │ Int64        Float64  Bool  
─────┼─────────────────────────────
   1 │           2  3.14159   true
   2 │           3  1.41421  false

In [15]:
# druga kolumna drugiego i trzeciego wiersza
df2[2:3, :Col2]

2-element Vector{Float64}:
 3.141592653589793
 1.4142135623730951

In [16]:
# druga i trzecia kolumna drugiego i trzeciego wiersza
df2[2:3,[:Col2, :Col3]]

2×2 DataFrame
 Row │ Col2     Col3  
     │ Float64  Bool  
─────┼────────────────
   1 │ 3.14159   true
   2 │ 1.41421  false

In [17]:
# pierwsze sześć wierszy
DataFrames.first(df2,6)

6×3 DataFrame
 Row │ MojaKolumna  Col2     Col3  
     │ Int64        Float64  Bool  
─────┼─────────────────────────────
   1 │           1  2.0       true
   2 │           2  3.14159   true
   3 │           3  1.41421  false
   4 │           4  3.0       true
   5 │           5  4.0      false
   6 │           6  2.0       true

In [18]:
# ostatnie sześć wierszy
DataFrames.last(df2,6)

6×3 DataFrame
 Row │ MojaKolumna  Col2     Col3  
     │ Int64        Float64  Bool  
─────┼─────────────────────────────
   1 │           5  4.0      false
   2 │           6  2.0       true
   3 │           7  3.14159   true
   4 │           8  1.41421  false
   5 │           9  3.0       true
   6 │          10  4.0      false

In [19]:
# nazwy kolumn
names(df2)

3-element Vector{String}:
 "MojaKolumna"
 "Col2"
 "Col3"

In [20]:
# typy kolumn
eltype.(eachcol(df2))

3-element Vector{DataType}:
 Int64
 Float64
 Bool

In [21]:
# podstawowe dane statystyczne o wartościach w kolumnie
describe(df2)

In [ ]:
using Statistics
mean(df2.Col2)

In [ ]:
var(df2.Col2)

In [ ]:
#Pkg.add("CSV")
using CSV
input="winequality.csv"
mydata=CSV.read(input, delim=";",DataFrame)

In [ ]:
describe(mydata)

In [ ]:
typeof(mydata)

In [ ]:
size(mydata)

## Dzielenie DataFrame na podgrupy i działania na nich

### Split - Apply - Combine

https://dataframes.juliadata.org/stable/man/split_apply_combine/


In [ ]:
# rozdzielanie na podgrupy po jakości wina (quality)
# Split
wine_grouped=groupby(mydata, :quality)

In [ ]:
# podsumowanie ile jest win w każdej grupie 
combine(wine_grouped, nrow)

In [ ]:
combine(wine_grouped, "fixed acidity" => mean)

In [ ]:
# zliczenie liczby win o danej jakości i zawartości alkoholu, posortowane
wine_grouped2=sort(combine(groupby(mydata, [:quality,:alcohol]),nrow=> :liczba), [:quality,:alcohol])

In [ ]:
# zapis do pliku
CSV.write("dataframe1.csv", wine_grouped2)


### Graficzna reprezentacja DataFrames




In [ ]:
using DataFrames
df = DataFrame(a = 1:10, b = map(x->2x,(1:10)), c = map(x->log(x),(1:10)), d=rand(10), e=map(x->x%2,(1:10)))

In [ ]:
# Mozna odwolywac sie bezposrednio do kolumn w poniższy sposób (gdyz sa typu jednowymiarowych tablic 
# Array{T,1})

using Plots
scatter(df.a, [df.b, df.c], colour = [:red :blue], yerr=df.d)


In [ ]:
# użycie opcji layout
scatter(df.a, [df.b, df.c],  colour = [:red :blue ], layout=2)

In [ ]:
# użycie opcji layout i group
scatter(df.a, [df.b, df.c], group=df.e,  colour = [:red :blue :green :black], layout=2)

Uwaga: Ze względu na specyfikę języka Julia pomiar czasu wykonania należy brać pod uwagę dopiero od drugiego wywołania danej funkcji
(za pierwszym razem mierzymy również czas kompilacji)

Makro @time - zwraca wartość funkcji i wypisuje czas jej trwania.
Makro @elapsed zwraca czas trwania (może być wygodniejsze w użyciu). 
Warto też oglądnąć działanie makr @timev, @timed, i @allocated

https://docs.julialang.org/en/v1/base/base/#Base.@time

Rand(10) - wylosuj 10-elementową tablicę Float64 z przedziału [0,1)

https://docs.julialang.org/en/v1/stdlib/Random/#Base.rand

### Zadanie 
- Napisać program w języku Julia do obliczania iloczynu skalarnego wektorów (<a href="https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.dot">LinearAlgebra.dot</a>) i mnożenia macierzy kwadratowej przez wektor z użyciem 
<a href="https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#Elementary-operations-1">operatora *</a>.
- Uruchomić i zmierzyć czasy działania obydwu funkcji - każdej dla różnych rozmiarów wektorów.  Dokonać 10 pomiarów dla każdego rozmiaru wektora.
- Czasy działania powinny  być zapisywane do <b>jednego</b> pliku CSV. Należy zaplanować odpowiednią strukturę kolumn takiego pliku.
- Wczytać dane z w/w pliku do <b>jednego</b> DataFrame w języku Julia. 
- Korzystająć z mechanizmów DataFrame w języku Julia obliczyć średnią i odchylenie standardowe, w taki sposób, aby narysować wykresy średnich czasów obliczenia operacji w zależności od rozmiaru wektora. Dodać słupki błędów do obydwu wykresów uzyskanych z obliczenia odchylenia standardowego. 
- Proszę poukładac wykresy  w tabelkę za pomocą  opcji layouts: https://docs.juliaplots.org/latest/layouts/#Simple-Layouts-1.
- Należy zadbać o staranne podpisanie osi i wykresów.